services:

    hive-metastore:
        container_name: hive-metastore
        depends_on:
            - postgres
        environment:
            AZURE_ABFS_ACCESS_KEY: ''
            AZURE_ABFS_OAUTH: ''
            AZURE_ABFS_OAUTH_CLIENT_ID: ''
            AZURE_ABFS_OAUTH_ENDPOINT: ''
            AZURE_ABFS_OAUTH_SECRET: ''
            AZURE_ABFS_OAUTH_TOKEN_PROVIDER: ''
            AZURE_ABFS_STORAGE_ACCOUNT: ''
            AZURE_ADL_CLIENT_ID: ''
            AZURE_ADL_CREDENTIAL: ''
            AZURE_ADL_REFRESH_URL: ''
            AZURE_WASB_ACCESS_KEY: ''
            AZURE_WASB_STORAGE_ACCOUNT: ''
            GOOGLE_CLOUD_KEY_FILE_PATH: ''
            HIVE_METASTORE_DRIVER: org.postgresql.Driver
            HIVE_METASTORE_JDBC_URL: jdbc:postgresql://postgres:5432/metastore
            HIVE_METASTORE_USER: hive
            HIVE_METASTORE_PASSWORD: hive
            HIVE_METASTORE_USERS_IN_ADMIN_ROLE: 'admin'
            REGION: ''
            S3_ACCESS_KEY: minio
            S3_ENDPOINT: http://minio:9000
            S3_PATH_STYLE_ACCESS: 'true'
            S3_SECRET_KEY: password
        hostname: hive-metastore
        image: 'starburstdata/hive:3.1.3-e.10'
        ports:
            - '9083:9083'

    minio:
        command: server /data --console-address ':9001'
        container_name: minio
        environment:
            MINIO_ROOT_PASSWORD: password
            MINIO_ROOT_USER: minio
        hostname: minio
        image: 'minio/minio:latest'
        ports:
            - '9000:9000'
            - '9001:9001'
        volumes:
            - ./data:/data
            - ./parquet:/parquet

    postgres:
        container_name: postgres
        environment:
            POSTGRES_DB: metastore
            POSTGRES_PASSWORD: hive
            POSTGRES_USER: hive
        hostname: postgres
        image: postgres:latest
        ports:
            - '5432:5432'

    trino:
        container_name: trino
        hostname: trino
        image: 'trinodb/trino:latest'
        ports:
            - '8080:8080'
        volumes:
            - ./etc/trino:/etc/trino
